version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
